### ISSUE TITLE
vue 2

### ISSUE THREAD

**Issue by nickmessing** [pksunkara/spoiler#4]
I guess it's time to migrate to vue 2.0, what about rewriting everything?

**Comment by pksunkara** [comment]
I don't understand. I am already using vue 2.0 as shown [here](https://github.com/pksunkara/spoiler/blob/master/template/package.json#L36). I keep this updated with the official webpack repo.

**Comment by nickmessing** [comment]
@pksunkara, sorry, started an empty project with another community boilerplate, my mistake ))
